// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBfssLhhXrFcGpBbSBsP-3JShCs8Zhhm0',
    appId: '1:128300883143:web:b774376de9e7c331cc32e2',
    messagingSenderId: '128300883143',
    projectId: 'kopma-suka',
    authDomain: 'kopma-suka.firebaseapp.com',
    storageBucket: 'kopma-suka.appspot.com',
    measurementId: 'G-F1NTQD19QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqfOFZnza7JlD1MpCXkclgqvtsgLgoNfQ',
    appId: '1:128300883143:android:a27bbfd5a3997abfcc32e2',
    messagingSenderId: '128300883143',
    projectId: 'kopma-suka',
    storageBucket: 'kopma-suka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHC0Oj35Bh4sEu7CsjLNJMxIQTA838UMo',
    appId: '1:128300883143:ios:dafb4cebd37f9d5ccc32e2',
    messagingSenderId: '128300883143',
    projectId: 'kopma-suka',
    storageBucket: 'kopma-suka.appspot.com',
    iosBundleId: 'com.example.kopma',
  );
}

const iOSClientId = 'your-client-id.apps.googleusercontent.com';
// const webClientId = '128300883143-m3ejeqk4a229j6eglpr4bl2t9ijicua9.apps.googleusercontent.com';
const webClientId = '959601409817-71n4ll7mpg6kss91lfu431crbnc1a3h8.apps.googleusercontent.com';


String get googleClientId {
  return switch (defaultTargetPlatform) {
    TargetPlatform.iOS || TargetPlatform.macOS => iOSClientId,
    _ => webClientId,
  };
}
